FROM hg2c/pilosa:latest as pilosa



FROM golang:alpine

RUN apk add --no-cache curl jq

ENV PILOSA_HOME="/opt/pilosa"
ENV PATH="${PILOSA_HOME}:${PATH}:/playground"

COPY --from=pilosa ${PILOSA_HOME} ${PILOSA_HOME}
COPY ./pdk ${PILOSA_HOME}/pdk

COPY playground /playground
WORKDIR /playground

VOLUME /data
CMD ["sh"]
