#!/usr/bin/env sh
source .env

run_pdk() {
    local PDK=/pdk
    echo $PDK -p $endpoint $*
    $PDK -p $endpoint $*
}


if [ "$1" = "taxi-big" ]; then
    run_pdk taxi -i taxi-big -f /opt/pdk/usecase/taxi/greenAndYellowUrls.txt
    exit
fi

run_pdk $*
